apiVersion: v1
kind: Service
metadata:
  name: broker-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - port: 32002
      targetPort: 32002
      nodePort: 32011
  externalTrafficPolicy: Cluster
