apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 32001
      targetPort: 32001
      nodePort: 32010
  externalTrafficPolicy: Cluster
